### ISSUE TITLE
Make repo name media source agnostic

### ISSUE THREAD

**Issue by syltruong** [ahmedbesbes/media-agent#5]
We want to give the user the option to ingest data from sources other than Twitter (eg. Substack or Reddit).

The repository name needs to reflect that.

Suggestions:
- `knowledge-agent`
- `ask-me-anything`
- `media-agent`

**Comment by ahmedbesbes** [comment]
I like media-agent 👍🏻

**Comment by ahmedbesbes** [comment]
Closing this issue after renaming the projet to media-agent

**Comment by ahmedbesbes** [comment]
Closing this issue after renaming the projet to media-agent
